name: "Automatic release"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: 16
    - name: "Run JS script"
      run: node $GITHUB_ACTION_PATH/auto.js
      shell: "bash"
    - name: Commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git push --follow-tags
