name: "Automatic release"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: 16
    - name: "get dependencies"
      run: cd $GITHUB_ACTION_PATH && npm install
      shell: "bash"
    - name: "Run JS script"
      run: node $GITHUB_ACTION_PATH/auto.js
      shell: "bash"
